### ISSUE TITLE
[Template] pb d'affichage d'un élément du model

### ISSUE THREAD

**Issue by jcheron** [LoicXIII/emberTds#3]
### Ressources
- Template
https://github.com/LoicXIII/emberTds/blob/2c192571b9868f40e309578a3a929e2e993aebfb/app/templates/project.hbs#L18-L38
- Route
https://github.com/LoicXIII/emberTds/blob/2c192571b9868f40e309578a3a929e2e993aebfb/app/routes/project.js#L6-L12

### Résultat attendu
Affichage du `developer` de chaque story (ligne 30) 
### Résultat obtenu
`{{story.developer}}` n'affiche rien
### Contexte
Ember-cli 3.12

**Comment by jcheron** [comment]
`{{story.developer}}` est un objet,
Il serait préférable de faire:
`{{story.developer.identity}}` pour afficher le nom du developer

**Comment by LoicXIII** [comment]
super ca fonctionne, merci !
